### 作业1 ： 1.9

In [29]:
# 构造矩阵
A <- matrix(1,3,3)
diag(A) <- c(2,2,2)
print(A)

     [,1] [,2] [,3]
[1,]    2    1    1
[2,]    1    2    1
[3,]    1    1    2


In [30]:
eigen(A) # 有三个特征根，一个是4，另外是1（重根）

eigen() decomposition
$values
[1] 4 1 1

$vectors
           [,1]       [,2]       [,3]
[1,] -0.5773503  0.0000000  0.8164966
[2,] -0.5773503 -0.7071068 -0.4082483
[3,] -0.5773503  0.7071068 -0.4082483


In [31]:
# 谱分解
P <- eigen(A)$vectors
A1 <- P %*% diag(eigen(A)$values) %*% t(P)
print(A1)

     [,1] [,2] [,3]
[1,]    2    1    1
[2,]    1    2    1
[3,]    1    1    2


In [47]:
A2 <- eigen(A)$values[1] * P[,1] %*% t(P[,1]) + eigen(A)$values[2] * P[,2] %*% t(P[,2]) + eigen(A)$values[3] * P[,3] %*% t(P[,3])
print(A2)

     [,1] [,2] [,3]
[1,]    2    1    1
[2,]    1    2    1
[3,]    1    1    2


### 第二次作业

In [4]:
sigma = rbind(c(9,1,-2),c(1,20,3),c(-2,3,12))
print(sigma)

     [,1] [,2] [,3]
[1,]    9    1   -2
[2,]    1   20    3
[3,]   -2    3   12


In [5]:
A = rbind(c(2,3,1),c(1,-2,5),c(0,1,-1))
print(A)

     [,1] [,2] [,3]
[1,]    2    3    1
[2,]    1   -2    5
[3,]    0    1   -1


In [8]:
A %*% sigma %*% t(A)

[,1] [,2] [,3]
[1,] 250  -26   48 
[2,] -26  305  -76 
[3,]  48  -76   26